### ISSUE TITLE
No module named 'ssas_api'

### ISSUE THREAD

**Issue by Clives-online** [yehoshuadimarsky/python-ssas#3]
Greetings,

I am trying to test the ssas_api module, but get an error when I try to import ssas_api??

The error message

"C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\python.exe" C:/Users/user/PycharmProjects/PowerBI/SSAS.py
Traceback (most recent call last):
  File "C:/Users/user/PycharmProjects/PowerBI/SSAS.py", line 132, in <module>
    @_assert_dotnet_loaded
  File "C:/Users/user/PycharmProjects/PowerBI/SSAS.py", line 103, in _assert_dotnet_loaded
    import ssas_api
ModuleNotFoundError: No module named 'ssas_api'

Process finished with exit code 1

**Comment by yehoshuadimarsky** [comment]
You must have your path set to the directory with the file.
